-- 코드를 작성해주세요

SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE FROM ECOLI_DATA AS A INNER JOIN ECOLI_DATA as B 
WHERE 
    B.ID = A.PARENT_ID AND A.GENOTYPE & B.GENOTYPE = B.GENOTYPE
ORDER BY A.ID